name: fast_common_module
description: A common Flutter module for role permission authentication, base services, and microservices architecture with multilingual support.
version: 1.0.4
homepage: https://github.com/Yazilim-Motoru/fastcommonmodule
repository: https://github.com/Yazilim-Motoru/fastcommonmodule.git
issue_tracker: https://github.com/Yazilim-Motoru/fastcommonmodule/issues
environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.2.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - lib/src/localization/l10n/en.json
    - lib/src/localization/l10n/tr.json